### ISSUE TITLE
Error: Cannot find module './util'

### ISSUE THREAD

**Issue by ForLoveOfCats** [69/fmcord#1]
OS: KDE Neon
Node Version: 8.4.0
npm Version: 5.5.1

All dependencies installed successfully, except for ```util``` which throws a compiler error. ```util``` has not been updated in years, is unmaintained, and fails to build. If ```util``` is not required by any dependency, would it be feasible to rework fmcord to no longer require ```util```?

```util``` Github URL: https://github.com/defunctzombie/node-util

**Comment by 69** [comment]
Pretty sure that's an issue with discord-rpc, which tries to require util.js (lower case) but actually has a file named Util.js in the same directory. This has been [fixed](https://github.com/devsnek/discord-rpc/commit/5a77802e3647c14c5b5468597ab339583027e5cb) in their Github repo but it doesn't look like it's been pushed to npm.

**Comment by ForLoveOfCats** [comment]
Good to know!
