### ISSUE TITLE
Autostart on Windows

### ISSUE THREAD

**Issue by ghost** [69/fmcord#6]
Any idea how to create a startup script with `pm2 start app.js --name="fmcord"` in it on Windows? Or any other "native" way to achieve the same goal.

**Comment by 69** [comment]
I believe something like [pm2-windows-startup](https://www.npmjs.com/package/pm2-windows-startup) would be suitable for this. Let me know if this works for you.

**Comment by ghost** [comment]
It worked, thanks.
